INSERT INTO public.nvr (id, ip, port, login, password) VALUES (1, '192.168.1.241', 34567, 'admin', '1qaz2wsx');
INSERT INTO public.nvr (id, ip, port, login, password) VALUES (2, '192.168.1.242', 34567, 'admin', '1qaz2wsx');
INSERT INTO public.nvr (id, ip, port, login, password) VALUES (3, '192.168.1.243', 34567, 'admin', '1qaz2wsx');
INSERT INTO public.nvr (id, ip, port, login, password) VALUES (4, '192.168.1.244', 34567, 'admin', '1qaz2wsx');

INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (1, 'МВН', 25, 0.5625, 1, 1, 'БКС', 'подвал', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (2, 'ВВН', 25, 0.5625, 1, 2, 'БКС', 'подвал', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (3, 'ГСТ', 25, 0.5625, 1, 3, 'БКС', 'подвал', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (4, 'ОН 1', 25, 0.5625, 1, 4, 'БКС', 'подвал', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (5, 'ВВН', 25, 0.5625, 1, 5, 'КЭС', 'подвал', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (6, 'ОН 2', 25, 0.5625, 1, 6, 'БКС', 'подвал', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (7, 'ОН 3', 25, 0.5625, 1, 7, 'КЭС', 'подвал', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (8, 'ОН 2', 25, 0.5625, 1, 8, 'КЭС', 'подвал', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (16, 'общий вид', 25, 0.5625, 2, 8, 'ОРУ', '1 этаж', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (9, 'ОН 1', 25, 0.5625, 2, 1, 'КЭС', 'подвал', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (33, 'вид на генератор', 25, 0.5625, 2, 10, 'КЭС', '5 этаж', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (10, 'ГСТ', 25, 0.5625, 2, 2, 'КЭС', 'подвал', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (11, 'МВН', 25, 0.5625, 2, 3, 'КЭС', 'подвал', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (12, 'ОН', 25, 0.5625, 2, 4, 'МКС', 'подвал', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (13, 'ВВН 2', 25, 0.5625, 2, 5, 'МКС', 'подвал', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (14, 'ВВН 1', 25, 0.5625, 2, 6, 'МКС', 'подвал', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (15, 'ГСТ', 25, 0.5625, 2, 7, 'МКС', 'подвал', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (22, 'вид 3', 25, 0.5625, 3, 6, 'СНИМ', '1 этаж', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (24, 'калибровка датчиков', 25, 0.5625, 3, 8, 'МКС', '2 этаж', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (17, 'дивертер', 25, 0.5625, 3, 1, 'ОРУ', '1 этаж', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (18, 'насос откачки 1', 25, 0.5625, 3, 2, 'ОРУ', '1 этаж', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (19, 'насос откачки 2', 25, 0.5625, 3, 3, 'ОРУ', '1 этаж', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (20, 'вид 1', 25, 0.5625, 3, 4, 'СНИМ', '1 этаж', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (21, 'вид 2', 25, 0.5625, 3, 5, 'СНИМ', '1 этаж', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (23, 'сварочная плита', 25, 0.5625, 3, 7, '1 этаж', '1 этаж', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (26, 'эл. Шкафы', 25, 0.5625, 4, 2, 'БКС', '2 этаж', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (25, 'эл. Шкафы', 25, 0.5625, 4, 1, 'МКС', '2 этаж', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (27, 'эл. Шкафы', 25, 0.5625, 4, 3, 'КЭС', '2 этаж', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (28, 'вид на моднль', 25, 0.5625, 4, 4, 'КЭС', '4 этаж', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (29, 'вид на моднль', 25, 0.5625, 4, 5, 'МКС', '5 этаж', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (30, 'вал ГСТ', 25, 0.5625, 4, 6, 'МКС', '5 этаж', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (31, 'вид на моднль', 25, 0.5625, 4, 7, 'БКС', '5 этаж', true);
INSERT INTO public.camera (id, name, rate, ratio, dvr, channel, stand, location, enable) VALUES (32, 'вал ГСТ', 25, 0.5625, 4, 8, 'БКС', '5 этаж', true);


INSERT INTO public.sensor (id, name, enable) VALUES (1, 'Давление ОРУ1', true);
INSERT INTO public.sensor (id, name, enable) VALUES (2, 'Давление ОРУ2', true);
INSERT INTO public.sensor (id, name, enable) VALUES (3, 'Давление ОРУ3', true);
INSERT INTO public.sensor (id, name, enable) VALUES (4, 'Давление ОРУ4', true);
INSERT INTO public.sensor (id, name, enable) VALUES (5, 'Давление ОРУ5', true);
INSERT INTO public.sensor (id, name, enable) VALUES (6, '(БКС)Давление ВВН', true);
INSERT INTO public.sensor (id, name, enable) VALUES (7, '(БКС) Давление МВН', true);
INSERT INTO public.sensor (id, name, enable) VALUES (8, '(КЭС) Давление ВВН', true);
INSERT INTO public.sensor (id, name, enable) VALUES (9, '(КЭС) Давление МВН', true);
INSERT INTO public.sensor (id, name, enable) VALUES (10, '(МКС)Давление ВВН №1', true);
INSERT INTO public.sensor (id, name, enable) VALUES (11, '(МКС) Давление ВВН №2', true);
INSERT INTO public.sensor (id, name, enable) VALUES (12, '(КЭС) Давление подачи в бак ГСТ', true);
INSERT INTO public.sensor (id, name, enable) VALUES (13, '(БКС) Давление подачи в бак ГСТ', true);
INSERT INTO public.sensor (id, name, enable) VALUES (14, '(МКС) Давление подачи в бак ГСТ', true);
INSERT INTO public.sensor (id, name, enable) VALUES (15, '(КЭС) Давление в магистрали питания ГСТ', true);
INSERT INTO public.sensor (id, name, enable) VALUES (16, '(БКС) Давление в магистрали питания ГСТ', true);
INSERT INTO public.sensor (id, name, enable) VALUES (17, '(МКС) Давление в магистрали питания ГСТ', true);
INSERT INTO public.sensor (id, name, enable) VALUES (18, '(БКС) Дым двигатель №1', true);
INSERT INTO public.sensor (id, name, enable) VALUES (19, '(БКС) Дым двигатель №2', true);
INSERT INTO public.sensor (id, name, enable) VALUES (20, '(БКС) Дым маслостанция', true);
INSERT INTO public.sensor (id, name, enable) VALUES (21, '(КЭС) Дым двигатель №1', true);
INSERT INTO public.sensor (id, name, enable) VALUES (22, '(КЭС) Дым двигатель №2', true);
INSERT INTO public.sensor (id, name, enable) VALUES (23, '(КЭС) Дым двигатель №3', true);
INSERT INTO public.sensor (id, name, enable) VALUES (24, '(КЭС) МВН', true);
INSERT INTO public.sensor (id, name, enable) VALUES (25, '(МКС) Дым двигатель', true);
INSERT INTO public.sensor (id, name, enable) VALUES (26, '(МКС) Дым маслостанция', true);
INSERT INTO public.sensor (id, name, enable) VALUES (27, '(ОРУ) Дым ОРУ', true);
INSERT INTO public.sensor (id, name, enable) VALUES (28, '(БКС) Гром - 12', true);
INSERT INTO public.sensor (id, name, enable) VALUES (29, '(МКС) Гром - 12', true);
INSERT INTO public.sensor (id, name, enable) VALUES (30, '(КЭС) Гром - 12', true);
INSERT INTO public.sensor (id, name, enable) VALUES (31, '(ОРУ) Гром - 12', true);
INSERT INTO public.sensor (id, name, enable) VALUES (32, '(СНИиМ) Гром - 12', true);
INSERT INTO public.sensor (id, name, enable) VALUES (33, '(БКС) Вибрация', true);
INSERT INTO public.sensor (id, name, enable) VALUES (34, '(КЭС) Вибрация', true);
INSERT INTO public.sensor (id, name, enable) VALUES (35, '(МКС) Вибрация', true);
INSERT INTO public.sensor (id, name, enable) VALUES (36, '(БКС) Протечка основная задвижка', true);
INSERT INTO public.sensor (id, name, enable) VALUES (37, '(БКС) Протечка подвал', true);
INSERT INTO public.sensor (id, name, enable) VALUES (38, '(БКС) Протечка стенд', true);
INSERT INTO public.sensor (id, name, enable) VALUES (39, '(КЭС) Протечка основная задвижка №2', true);
INSERT INTO public.sensor (id, name, enable) VALUES (40, '(КЭС) Протечка подвал', true);
INSERT INTO public.sensor (id, name, enable) VALUES (41, '(КЭС) Протечка стенд', true);
INSERT INTO public.sensor (id, name, enable) VALUES (42, '(МКС) Протечка ВВН1', true);
INSERT INTO public.sensor (id, name, enable) VALUES (43, '(МКС) Протечка подвал', true);
INSERT INTO public.sensor (id, name, enable) VALUES (44, '(МКС) Протечка стенд', true);
INSERT INTO public.sensor (id, name, enable) VALUES (45, '(ОРУ) Протечка насос СЗВО', true);
INSERT INTO public.sensor (id, name, enable) VALUES (46, '(ОРУ) Протечка перелив шахты ', true);
INSERT INTO public.sensor (id, name, enable) VALUES (47, '(СНИиМ) Протечка стенды', true);
INSERT INTO public.sensor (id, name, enable) VALUES (48, '(БКС)Температура ВВН', true);
INSERT INTO public.sensor (id, name, enable) VALUES (49, '(БКС)Температура Гидростатика', true);
INSERT INTO public.sensor (id, name, enable) VALUES (50, '(БКС)Температура МВН', true);
INSERT INTO public.sensor (id, name, enable) VALUES (51, '(КЭС)Температура ВВН', true);
INSERT INTO public.sensor (id, name, enable) VALUES (52, '(КЭС)Температура Гидростатика', true);
INSERT INTO public.sensor (id, name, enable) VALUES (53, '(КЭС)Температура МВН', true);
INSERT INTO public.sensor (id, name, enable) VALUES (54, '(МКС)Температура ВВН №1', true);
INSERT INTO public.sensor (id, name, enable) VALUES (55, '(МКС)Температура ВВН №2', true);
INSERT INTO public.sensor (id, name, enable) VALUES (56, '(МКС)Температура Гидростатика', true);
INSERT INTO public.sensor (id, name, enable) VALUES (57, 'Оптоствор ОРУ', true);
INSERT INTO public.sensor (id, name, enable) VALUES (58, 'Оптоствор БКС', true);
INSERT INTO public.sensor (id, name, enable) VALUES (59, 'Оптоствор КЭС1', true);
INSERT INTO public.sensor (id, name, enable) VALUES (60, 'Оптоствор КЭС2', true);
INSERT INTO public.sensor (id, name, enable) VALUES (61, 'Оптоствор МКС', true);

INSERT INTO public.alert (id, camera, device, value, processed, time) VALUES (1, 1, 1, 1, true, '2020-08-10 21:09:04.081000');